### PR TITLE
ci: add dependabot

### PR DESCRIPTION
**Pull request by untereiner**

### CODE REVIEW

**Review by cssherman — APPROVED** [review]
Looks good to me - have you worked with dependabot before?  Given the config, what do you expect the alerts look like?

**Comment by untereiner** [comment]
It should look like this one: https://github.com/GEOS-DEV/GEOS/pull/3154
I think I can also assign the PR to someone to merge it.

**Comment by untereiner** [comment]
I added you to the reviewer list. Let's try it.

**Comment by cssherman** [comment]
@untereiner - looking at the failed test, it seems like the network may be causing some issues with pip install (see https://stackoverflow.com/questions/71435874/pip-these-packages-do-mot-match-the-hashes-from-the-requirements-file).  Thoughts?

**Comment by untereiner** [comment]
It seems very arbitrary.
I know more poetry. I found a tuto to [build and publish](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) but didn’t find a good one for linting and testing. Do we agree that testing is the only reason to install locally in the ci the dependencies ?

**Comment by untereiner** [comment]
I would avoid the « requirements.txt not in the repo » thing by using tox for testing. Python guys are sometimes quite fool see https://github.com/pypa/pip/issues/11440

**Comment by untereiner** [comment]
@cssherman I think the test workflow could be updated but it should be in another PR. 
I propose to merge this one and I will open a new one for this subject.

**Pull request merged**
