### PR TITLE
feat: Python interfaces to geos from Makutu repo

### PR DESCRIPTION
**Pull request by av-novikov**
This PR merges some Python interfaces to GEOS from Makutu repository. These interfaces are coming as a part of [GEOS: PR 3391](https://github.com/GEOS-DEV/GEOS/pull/3391) and required to simplify interactions with GEOS from Python.

- [x] place interfaces to pygeos-tools

### CODE REVIEW

**Comment by untereiner** [comment]
as a minor comment: change `# Copyright (c) 2018-2024 Total, S.A` to `# Copyright (c) 2018-2024 TotalEnergies` as (partially) done in the GEOS repo (see PR #1562)

**Review by Bubusch — APPROVED** [review]
Thanks @av-novikov, looks good.
@sframba @Victor-M-Gomes  maybe at some point we can move all pygeos-tools/utilities up under pygeos-tools/ and make the package a bit more flat. We might also have to set some constraints on dependencies versions when installing on ppc architecture.

**Comment by alexbenedicto** [comment]
@av-novikov Hello! I am currently working in the _geos-mesh_ repository, which includes Python packages for pre-processing VTK grids, specifically through a tool called _mesh_doctor_.

I've noticed that some of the features you are adding might overlap with existing functionalities in _mesh_doctor_. To avoid redundancy, I suggest we collaborate to identify and merge these features effectively. This way, we can enhance _mesh_doctor_ without duplicating efforts across two repositories. I'm happy to assist with this process.

@cssherman, what are your thoughts on this approach?

**Comment by av-novikov** [comment]
> Thanks @av-novikov, looks good. @sframba @Victor-M-Gomes maybe at some point we can move all pygeos-tools/utilities up under pygeos-tools/ and make the package a bit more flat. We might also have to set some constraints on dependencies versions when installing on ppc architecture.

fixed, thanks!


> @av-novikov Hello! I am currently working in the geos-mesh repository, which includes Python packages for pre-processing VTK grids, specifically through a tool called mesh_doctor.

> I've noticed that some of the features you are adding might overlap with existing functionalities in mesh_doctor. To avoid redundancy, I suggest we collaborate to identify and merge these features effectively. This way, we can enhance mesh_doctor without duplicating efforts across two repositories. I'm happy to assist with this process.

Dear @alexbenedicto, thanks for looking inside! I can imagine that some of this functionality my overlap with existing and I am happy to contribute to the further development of the Python side of GEOS. However, this particular functionality is taken from Makutu-team repo as is. Thus, it is better to coordinate further its modification with Makutu developers, e.g. with @sframba.

**Comment by CusiniM** [comment]
I am reverting this merge. The repository had no restrictions in place but PRs this large should not be merged with a single approving reviewer, especially considering that there was a comment by @alexbenedicto pointing out that he would have liked to discuss how to proceed considering the amount of duplicated capabilities. 

Please discuss with @alexbenedicto about how to proceed before remerging this.

**Pull request merged**
