### PR TITLE
Invalid packages import for geos-mesh, impacting documentation

### PR DESCRIPTION
**Pull request by alexbenedicto**
Linked to #29 
Geos-mesh feature files could not import packages from "src" correctly,
showing import errors in the documentation.

### CODE REVIEW

**Comment by untereiner** [comment]
seems not to be enough

**Comment by alexbenedicto** [comment]
I tried the sphinx-build with all .rst files and weirdly, certain of them raise an error when reaching this line :

`with mock(self.config.autodoc_mock_imports):`

Do you know @untereiner if I can contact someone to help me with the sphinx-build ?

**Comment by alexbenedicto** [comment]
The sphinx-build works on my side, generating the complete documentation.
I keep investigating it

**Comment by untereiner** [comment]
`\` is for windows filesytems. I suggest to keep `/`

**Comment by alexbenedicto** [comment]
@untereiner It appeared to be a sphinx / sphinx-argparse update required for the modules to be now recognized.
Regarding "\", I used to receive Warnings when using "/".
Do you want me to switch it back to "/' ?

**Comment by alexbenedicto** [comment]
@untereiner I think it's ok now to merge

**Review by untereiner — APPROVED** [review]

**Pull request merged**
